// src/components/uofg-header.svelte
<svelte:options
  customElement={{
    tag: 'uofg-header',
    props: {
      pageTitle: { reflect: true, type: 'String', attribute: 'page-title' },
      pageURL: { reflect: true, type: 'String', attribute: 'page-url' },
    },
    extend: customElementConstructor => {
      return class extends customElementConstructor {
        constructor() {
          super();
          attachTailwind(this.shadowRoot);
        }
        connectedCallback() {
          super.connectedCallback();

          this.updateSubNavigation();

          this.observer ??= new MutationObserver(() => {
            this.updateSubNavigation();
          });

          this.observer.observe(this, { childList: true, subtree: true });
        }
        disconnectedCallback() {
          super.disconnectedCallback();
          this.observer.disconnect();
        }
        updateSubNavigation() {
          const aToSubNavigationLink = a => {
            const attributes = {};
            a.getAttributeNames()
              .filter(name => name !== 'href')
              .forEach(name => (attributes[name] = a.getAttribute(name)));

            return {
              href: a.getAttribute('href'),
              text: a.textContent,
              attributes,
            };
          };

          this.subNavigation = Array.from(this.children)
            .filter(child => child.tagName === 'A' || child.tagName === 'UL')
            .map(child => {
              switch (child.tagName) {
                case 'A':
                  return aToSubNavigationLink(child);
                case 'UL':
                  const value = {
                    title: child.getAttribute('data-title'),
                    links: Array.from(child.querySelectorAll('a')).map(aToSubNavigationLink),
                  };

                  value.wrapContent = value.links.reduce((shouldWrap, link) => {
                    if (link.text.length > MENU_CHAR_LIMIT) {
                      shouldWrap = true;
                    }

                    return shouldWrap;
                  }, false);

                  return value;
              }
            })
            .filter(val => Boolean(val));
        }
      };
    },
  }}
/>

<script>
  import attachTailwind from '../lib/attach-tailwind.js';
  import Menu from '../lib/menu.svelte';
  import FontAwesomeIcon from '../lib/font-awesome-icon.svelte';
  import { faBars, faChevronDown, faSearch, faUser } from '@fortawesome/free-solid-svg-icons';
  import Logo from '../svg/logo.svg';
  import LogoSmall from '../svg/logo-small.svg';
  import Decorative from '../svg/decorative.svg';

  const BREAKPOINT = 1024;
  const MENU_CHAR_LIMIT = 35;

  const topLinks = [
    {
      text: 'Give',
      href: 'https://bbis.alumni.uoguelph.ca/BBIS_Cannon/give/uofg',
    },
    {
      text: 'News',
      href: 'https://news.uoguelph.ca/',
    },
    {
      text: 'Quick Links',
      links: [
        {
          text: 'Future Students',
          href: 'https://uoguelph.ca/future-ready',
        },
        {
          text: 'Current Students',
          href: 'https://www.uoguelph.ca/students',
        },
        {
          text: 'Alumni & Donors',
          href: 'https://alumni.uoguelph.ca/',
        },
        {
          text: 'Faculty & Staff',
          href: 'https://www.uoguelph.ca/faculty',
        },
        {
          text: 'Employers & Partners',
          href: 'https://cecs.uoguelph.ca/employers-institutions',
        },
      ],
    },
    {
      text: 'APPLY NOW',
      href: 'https://uoguelph.ca/apply/',
      highlight: true,
    },
  ];

  const mainLinks = [
    {
      text: 'About',
      href: 'https://uoguelph.ca/about',
    },
    {
      text: 'Academics',
      href: 'https://www.uoguelph.ca/explore-all-programs/',
    },
    {
      text: 'Admission',
      href: 'https://uoguelph.ca/admissions',
    },
    {
      text: 'Research',
      href: 'https://uoguelph.ca/research',
    },
    {
      text: 'Student Life',
      href: 'https://www.uoguelph.ca/studentexperience/',
    },
  ];

  const search = {
    text: 'Search the University of Guelph',
    href: 'https://uoguelph.ca/search',
    icon: faSearch,
  };

  const account = {
    text: 'Account Menu',
    links: [
      {
        text: 'Intranet',
        href: 'https://intranet.uoguelph.ca/',
      },
      {
        text: 'WebAdvisor',
        href: 'https://www.uoguelph.ca/webadvisor/',
      },
      {
        text: 'GryphMail',
        href: 'https://mail.uoguelph.ca/',
      },
      {
        text: 'CourseLink',
        href: 'https://courselink.uoguelph.ca/',
      },
      {
        text: 'GryphLife',
        href: 'https://gryphlife.uoguelph.ca/',
      },
    ],
    icon: faUser,
  };

  let windowWidth;
  let subNavigationElement;
  let subNavigationIsOverflowing = false;

  export let subNavigation;
  export let pageTitle;
  export let pageURL;

  $: {
    window.requestAnimationFrame(() => {
      if (windowWidth >= BREAKPOINT && subNavigationElement && !subNavigationIsOverflowing) {
        subNavigationIsOverflowing = subNavigationElement.offsetWidth > subNavigationElement.parentElement.offsetWidth;
      }
    });
  }
</script>

<svelte:window bind:innerWidth={windowWidth} />

<header class="relative z-10 w-full font-condensed text-3xl text-black">
  {#if windowWidth >= BREAKPOINT}
    <!-- Top Navigation Bar -->
    <nav class="flex h-16 justify-end bg-white px-[calc((100%-theme(spacing.max-content-width))/2)] text-3xl" aria-label="Secondary">
      <!-- Top Navigation Links -->

      <ul class="flex h-full items-center justify-end [&>li]:contents">
        {#each [...topLinks, account] as item (item.text || item.title)}
          <li>
            {#if item.links}
              <Menu
                class="relative h-full"
                buttonClass={`flex h-full items-center justify-center gap-2 px-4 transition-colors hover:bg-uofg-grey aria-expanded:bg-uofg-grey ${item.icon ? '' : '[&_svg]:aria-expanded:rotate-180'}`}
                contentClass="absolute right-0 top-full z-50 flex min-w-[20rem] flex-col bg-uofg-grey [&>li]:contents"
                as="ul"
                buttonAriaLabel={item.icon ? item.text : undefined}

              >
                <span
                  class="flex gap-2 [&>svg]:transition-transform"
                  class:bg-uofg-yellow={item.highlight}
                  slot="button"
                >
                  {#if item.icon}
                    <FontAwesomeIcon icon={item.icon} />
                  {:else}
                    <span>{item.text.toUpperCase()}</span>
                    <FontAwesomeIcon icon={faChevronDown} />
                  {/if}
                </span>

                {#each item.links as link}
                  <li>
                    <a
                      class="border-0 border-b border-solid border-uofg-grey-500 p-4 transition-colors hover:bg-uofg-yellow"
                      href={link.href}
                      {...link.attributes}
                    >
                      {link.text}
                    </a>
                  </li>
                {/each}
              </Menu>
            {:else}
              <a
                class="flex h-full items-center justify-center gap-2 px-4 transition-colors hover:bg-uofg-grey"
                class:bg-uofg-yellow={item.highlight}
                href={item.href}
              >
                {item.text.toUpperCase()}
              </a>
            {/if}
          </li>
        {/each}
      </ul>
    </nav>
  {/if}

  <div class="flex h-[5rem] lg:h-[10rem] bg-black">
  <!-- Main Navigation Bar -->
    <!-- Decorative SVG -->
    {#if windowWidth >= BREAKPOINT}
      <div class="left-0 h-full w-[7.5rem] [&>svg]:block [&>svg]:h-full [&>svg]:w-auto">
        <Decorative />
      </div>
    {/if}

  <nav
    class="relative w-full justify-between flex h-full pr-[calc((100%-theme(spacing.max-content-width))/2)] pl-[calc(((100%-theme(spacing.max-content-width))/2)-7.5rem)] text-3xl text-white"
    aria-label="Primary"
  >
    <!-- Logo -->
    <div class="flex w-fit">
      <a
        class={`flex h-full w-fit transition-opacity focus:opacity-75 hover:opacity-75 min-[theme(spacing.max-content-width)]:absolute min-[theme(spacing.max-content-width)]:left-[max(calc((100%-theme(spacing.max-content-width))/2),7.5rem)] [&>svg]:block [&>svg]:h-full ${windowWidth >= BREAKPOINT ? '[&>svg]:w-[18.4rem]' : '[&>svg]:w-[5rem]'}`}
        href="https://www.uoguelph.ca"
        aria-label="University of Guelph Home Page"
      >
        {#if windowWidth >= BREAKPOINT}
          <Logo />
        {:else}
          <LogoSmall />
        {/if}
      </a>
    </div>

    {#if windowWidth >= BREAKPOINT}
      <!-- Desktop Main Nagivation Items -->
      <ul class="flex ml-auto [&>li]:contents text-4xl">
        {#each mainLinks as item}
          <li>
            <a
              class="flex h-full items-center justify-center border-0 border-b-8 border-solid border-transparent p-6 pt-8 transition-colors hover:border-uofg-yellow hover:text-uofg-yellow"
              href={item.href}
            >
              {item.text}
            </a>
          </li>
        {/each}
        <!-- Search -->
        <li>
          <a
            class="flex h-full items-center justify-center border-0 border-b-8 border-solid border-transparent p-4 pb-6 pt-8 text-uofg-yellow transition-colors hover:border-uofg-yellow hover:text-white [&>svg]:fill-current"
            href={search.href}
            aria-label={search.text}
          >
            <FontAwesomeIcon icon={search.icon} />
          </a>
        </li>
      </ul>
    {:else}
      <!-- Mobile Main Nagivation Items -->
      <!-- Search -->
      <ul class="flex h-full [&>li]:contents">
        <li>
          <a
            class="flex h-full aspect-square items-center justify-center gap-2 px-4 transition-colors hover:bg-white focus:bg-white aria-expanded:bg-white hover:text-black focus:text-black aria-expanded:text-black"
            href={search.href}
            aria-label={search.text}
          >
            <FontAwesomeIcon icon={search.icon} />
          </a>
        </li>

        <!-- Account Menu -->
        <li>
          <Menu
            class="h-full"
            buttonClass="flex h-full aspect-square items-center justify-center gap-2 px-4 transition-colors hover:bg-white focus:bg-white aria-expanded:bg-white hover:text-black focus:text-black aria-expanded:text-black"
            contentClass="absolute right-0 top-full z-50 flex w-full flex-col bg-white px-4 text-black shadow-md lg:w-[30rem] [&>li]:contents"
            as="ul"
          >
            <FontAwesomeIcon slot="button" icon={account.icon} />

            {#each account.links as link}
              <li class="[&>*]:first:mt-4 [&>*]:last:mb-4">
                <a
                  class="border-0 border-b border-solid border-uofg-grey-500 p-4 transition-colors hover:bg-uofg-yellow"
                  href={link.href}
                >
                  {link.text}
                </a>
              </li>
            {/each}
          </Menu>
        </li>
        <!-- Main Menu -->
        <li>
          <Menu
            class="h-full"
            buttonClass="flex h-full aspect-square items-center justify-center gap-2 px-4 transition-colors hover:bg-white focus:bg-white aria-expanded:bg-white hover:text-black focus:text-black aria-expanded:text-black [&_svg]:aria-expanded:rotate-180"
            contentClass="absolute right-0 top-full z-50 flex w-full flex-col bg-white px-4 text-black shadow-md lg:w-[30rem] [&>li]:contents max-h-[calc(100vh-5rem)] overflow-y-auto"
            as="ul"
          >
            <FontAwesomeIcon slot="button" icon={faBars} />

            {#each [...mainLinks, ...topLinks] as item}
              <li class="[&>*]:first:mt-4 [&>*]:last:mb-4">
                {#if item.links}
                  <Menu
                    class="relative w-full"
                    buttonClass="flex border-0 border-b border-solid border-uofg-grey-500 w-full items-center justify-between gap-2 p-4 transition-colors hover:bg-uofg-grey focus:bg-uofg-grey aria-expanded:bg-uofg-grey [&_svg]:aria-expanded:rotate-180"
                    contentClass="flex flex-col w-full flex-col bg-white text-black [&>li]:contents"
                    as="ul"
                    autoCollapse={false}
                  >
                    <span
                      class="w-full flex gap-2 justify-between [&>svg]:transition-transform"
                      class:bg-uofg-yellow={item.highlight}
                      slot="button"
                    >
                      <span class="mr-auto">{item.text}</span>
                      <FontAwesomeIcon icon={faChevronDown} />
                    </span>

                    {#each item.links as link}
                      <li>
                        <a
                          class="border-0 border-b border-solid border-uofg-grey-500 p-4 transition-colors hover:bg-uofg-grey"
                          href={link.href}
                          {...link.attributes}
                        >
                          {link.text}
                        </a>
                      </li>
                    {/each}
                  </Menu>
                {:else}
                  <a
                    class="border-0 border-b border-solid border-uofg-grey-500 p-4 transition-colors hover:bg-uofg-grey focus:bg-uofg-grey"
                    class:bg-uofg-yellow={item.highlight}
                    href={item.href}
                  >
                    {item.text}
                  </a>
                {/if}
              </li>
            {/each}
          </Menu>
        </li>
      </ul>
    {/if}
  </nav>
  </div>
  <!-- Sub Navigation Bar -->
  {#if subNavigation.length > 0 || pageTitle}
    <nav
      class="block align-items relative h-[5rem] justify-end bg-uofg-grey px-[calc((100%-theme(spacing.max-content-width))/2)] text-3xl lg:h-16 lg:whitespace-nowrap"
      aria-label="Page Specific"
    >
      <ul
        class="flex h-full w-fit min-w-full overflow-y-visible items-center justify-end [&>li]:contents relative"
        bind:this={subNavigationElement}
      >
        <!-- Page/Department/Topic Title -->
        {#if pageTitle}
          <li>
            {#if pageURL}
              <a
                class="mr-auto flex h-full items-center justify-center px-4 font-bold transition-colors hover:bg-uofg-yellow"
                href={pageURL}
              >
                {pageTitle}
              </a>
            {:else}
              <span class="mr-auto flex h-full items-center justify-center px-4 font-bold">
                {pageTitle}
              </span>
            {/if}
          </li>
        {/if}

        {#if windowWidth >= BREAKPOINT && !subNavigationIsOverflowing}
          <!-- Desktop Sub Navigation Links and Menus -->
          <li>
            {#each subNavigation as item (item.text || item.title)}
              {#if item.text}
                <!-- Link -->

                <a
                  {...item.attributes}
                  class={`flex h-full items-center justify-center gap-2 px-4 transition-colors hover:bg-uofg-yellow ${item.attributes?.class ?? ""}`}
                  href={item.href}
                >
                  {item.text}
                </a>
              {:else}
                <!-- Menu -->

                <Menu
                  class="relative h-full"
                  buttonClass="flex h-full items-center justify-center gap-2 px-4 transition-colors hover:bg-uofg-yellow aria-expanded:bg-uofg-yellow [&_svg]:aria-expanded:rotate-180"
                  contentClass="absolute right-0 top-full z-50 flex min-w-[20rem] flex-col bg-uofg-grey [&>li]:contents"
                  as="ul"
                >
                  <span class="flex gap-2 [&>svg]:transition-transform" slot="button">
                    <span>{item.title}</span>
                    <FontAwesomeIcon icon={faChevronDown} />
                  </span>

                  {#each item.links as link}
                    <li>
                      <a
                        {...link.attributes}
                        class={`border-0 border-b border-solid border-uofg-grey-500 p-4 transition-colors hover:bg-uofg-yellow ${link.attributes?.class ?? ""}`}
                        href={link.href}
                      >
                        {link.text}
                      </a>
                    </li>
                  {/each}
                </Menu>
              {/if}
            {/each}
          </li>
          <!-- Mobile Sub Navigation Links and Menus -->
        {:else}
          <Menu
            class="h-full"
            buttonClass="flex h-full aspect-square items-center justify-center gap-2 px-4 transition-colors hover:bg-uofg-yellow aria-expanded:bg-uofg-yellow"
            contentClass="whitespace-normal absolute right-0 top-full z-50 flex w-full flex-col bg-white px-4 text-black shadow-md lg:w-[30rem] [&>li]:contents max-h-[calc(100vh-5rem)] overflow-y-auto"
            as="ul"
          >
            <FontAwesomeIcon slot="button" icon={faBars} />

            {#each subNavigation as item (item.text || item.title)}
              <li class="[&>*]:last:mb-4 [&>*]:first:mt-4">
                {#if item.text}
                  <!-- Link -->
                  <a
                    {...item.attributes}
                    class={`border-0 border-b border-solid border-uofg-grey-500 p-4 transition-colors hover:bg-uofg-grey ${item.attributes?.class ?? ""}`}
                    href={item.href}
                  >
                    {item.text}
                  </a>
                {:else}
                  <!-- Nested Menu -->
                  <Menu
                    class="relative w-full"
                    buttonClass="flex border-0 border-b border-solid border-uofg-grey-500 w-full items-center justify-between gap-2 p-4 transition-colors hover:bg-uofg-grey focus:bg-uofg-grey aria-expanded:bg-uofg-grey [&_svg]:aria-expanded:rotate-180"
                    contentClass="flex flex-col w-full flex-col bg-white text-black [&>li]:contents"
                    as="ul"
                    autoCollapse={false}
                  >
                    <span class="w-full flex gap-2 justify-between [&>svg]:transition-transform" slot="button">
                      <span class="mr-auto">{item.title}</span>
                      <FontAwesomeIcon icon={faChevronDown} />
                    </span>

                    {#each item.links as link}
                      <li>
                        <a
                          {...link.attributes}
                          class={`border-0 border-b border-solid border-uofg-grey-500 p-4 transition-colors hover:bg-uofg-grey ${link.attributes?.class ?? ""}`}
                          href={link.href}
                        >
                          {link.text}
                        </a>
                      </li>
                    {/each}
                  </Menu>
                {/if}
              </li>
            {/each}
          </Menu>
        {/if}
      </ul>
    </nav>
  {/if}
</header>

// src/components/uofg-header/uofg-header.tsx
import { Component, Element, h, Listen, Prop, State } from '@stencil/core';
import Decoration from './decoration.svg';
import FullSizeLogo from './logo-full.svg';
import ReducedSizeLogo from './logo-reduced.svg';
import { FontAwesomeIcon } from '../../utils/font-awesome-icon';
import { faBars } from '@fortawesome/free-solid-svg-icons/faBars';
import { faRightToBracket } from '@fortawesome/free-solid-svg-icons/faRightToBracket';
import { faSearch } from '@fortawesome/free-solid-svg-icons/faSearch';
import { faCaretDown } from '@fortawesome/free-solid-svg-icons/faCaretDown';
import { IconDefinition } from '@fortawesome/free-solid-svg-icons';

interface PageSpecificLink {
  text: string;
  href: string;
  attributes?: Record<string, string>;
}

interface PageSpecificSubMenu {
  title: string;
  links: PageSpecificLink[];
  wrapContent?: boolean;
}

type PageSpecificContent = Array<PageSpecificLink | PageSpecificSubMenu>;

type HeaderLink = {
  text: string;
  href: string;
  highlight?: boolean;
  icon?: IconDefinition;
};

type HeaderMenu = {
  text: string;
  links: HeaderLink[];
};

const TRANSITION_BREAKPOINT = 1024;
const MAX_CONTENT_WIDTH = 1320;
const MENU_CHAR_LIMIT = 35;

const topLinks: (HeaderLink | HeaderMenu)[] = [
  {
    text: 'Give',
    href: 'https://bbis.alumni.uoguelph.ca/BBIS_Cannon/give/uofg',
  },
  {
    text: 'News',
    href: 'https://news.uoguelph.ca/',
  },
  {
    text: 'Resources',
    links: [
      {
        text: 'Future Students',
        href: 'https://uoguelph.ca/future-students',
      },
      {
        text: 'Current Students',
        href: 'https://www.uoguelph.ca/students',
      },
      {
        text: 'Alumni & Donors',
        href: 'https://alumni.uoguelph.ca/',
      },
      {
        text: 'Faculty & Staff',
        href: 'https://www.uoguelph.ca/faculty',
      },
      {
        text: 'Employers & Partners',
        href: 'https://cecs.uoguelph.ca/employers-institutions',
      },
    ],
  },
  {
    text: 'APPLY',
    href: 'https://uoguelph.ca/apply/',
    highlight: true,
  },
];

const mainLinks: HeaderLink[] = [
  {
    text: 'About',
    href: 'https://uoguelph.ca/about',
  },
  {
    text: 'Academics',
    href: 'https://www.uoguelph.ca/explore-all-programs/',
  },
  {
    text: 'Admission',
    href: 'https://uoguelph.ca/admissions',
  },
  {
    text: 'Research',
    href: 'https://uoguelph.ca/research',
  },
  {
    text: 'Student Life',
    href: 'https://www.uoguelph.ca/studentexperience/',
  },
];

const iconButtons: HeaderLink[] = [
  {
    text: 'University of Guelph Intranet',
    href: 'https://intranet.uoguelph.ca/',
    icon: faRightToBracket,
  },
  {
    text: 'Search the University of Guelph',
    href: 'https://uoguelph.ca/search',
    icon: faSearch,
  },
];

@Component({ tag: 'uofg-header', styleUrl: 'uofg-header.css', shadow: true })
export class UofgHeader {
  /**
   * The title of the department/topic that the header is being used for. For example, for the Convocation pages, this would be set to "Convocation".
   */
  @Prop() pageTitle: string = '';

  /**
   * The URL to the home/landing page of the department/topic the header is being used for. For example, for the Convocation pages, this would be set to "https://www.uoguelph.ca/convocation/".
   */
  @Prop() pageUrl: string = '';

  @Element() el: HTMLUofgHeaderElement;
  @State() isFullSize: boolean = false;
  @State() pageSpecificContent: PageSpecificContent;
  private observer: MutationObserver;
  private subContainer?: HTMLElement;
  private subContainerOverflowWidth: number = NaN;
  @State() isSubContainerOverflowing: boolean = false;
  private needsOverflowWidthUpdate: boolean = false;

  connectedCallback() {
    this.updateFullSize();
    this.updatePageSpecificContent();

    this.observer ??= new MutationObserver(() => {
      this.updatePageSpecificContent();
      this.subContainerOverflowWidth = NaN; // Reset overflow width as it will have changed and needs to be recalculated
      this.needsOverflowWidthUpdate = true;
    });
    this.observer.observe(this.el, { childList: true, subtree: true });
  }

  componentDidLoad() {
    this.updateSubContainerOverflow();
  }

  @Listen('resize', { target: 'window' })
  updateFullSize() {
    this.isFullSize = window.innerWidth >= TRANSITION_BREAKPOINT;
    this.updateSubContainerOverflow();
  }

  private updateSubContainerOverflow() {
    if (this.isFullSize && this.subContainer) {
      const { clientWidth, scrollWidth } = this.subContainer;

      if (scrollWidth > clientWidth) {
        this.subContainerOverflowWidth = scrollWidth;
      }

      this.isSubContainerOverflowing = this.subContainerOverflowWidth > Math.min(clientWidth, MAX_CONTENT_WIDTH);
    }
  }

  componentDidRender() {
    if (this.needsOverflowWidthUpdate) {
      window.requestAnimationFrame(() => this.updateSubContainerOverflow());
      this.needsOverflowWidthUpdate = false;
    }
  }

  private updatePageSpecificContent() {
    const aToPageSpecificLink = (a: HTMLAnchorElement) => {
      const attributes = {};
      a.getAttributeNames()
        .filter(name => name !== 'href')
        .forEach(name => (attributes[name] = a.getAttribute(name)));

      return {
        href: a.getAttribute('href'),
        text: a.textContent,
        attributes,
      } as PageSpecificLink;
    };

    this.pageSpecificContent = Array.from(this.el?.children)
      .filter(child => child.tagName === 'A' || child.tagName === 'UL')
      .map(child => {
        switch (child.tagName) {
          case 'A':
            return aToPageSpecificLink(child as HTMLAnchorElement);
          case 'UL':
            const value = {
              title: child.getAttribute('data-title'),
              links: Array.from(child.querySelectorAll('a')).map(aToPageSpecificLink),
            } as PageSpecificSubMenu;

            value.wrapContent = value.links.reduce((shouldWrap, link) => {
              if (link.text.length > MENU_CHAR_LIMIT) {
                shouldWrap = true;
              }

              return shouldWrap;
            }, false);

            return value;
        }
      })
      .filter(val => Boolean(val)) as PageSpecificContent;
  }

  render() {
    return (
      <header class="tw-relative tw-z-[1000] tw-w-full tw-font-condensed tw-text-2xl tw-text-black">
        {/* Top Navigation Bar */}
        {this.isFullSize && (
          <div class="tw-flex tw-h-16 tw-justify-end tw-bg-white tw-px-[calc((100%-1320px)/2)] tw-text-3xl">
            <ul class="tw-contents [&>li]:tw-contents">
              {topLinks.map(item => {
                if ('links' in item) {
                  return (
                    <li>
                      <uofg-menu class="tw-relative tw-block tw-h-full" auto-collapse={true}>
                        <button
                          class="tw-flex tw-h-full tw-items-center tw-justify-center tw-gap-2 tw-transition-colors hover:tw-bg-uofg-grey aria-expanded:tw-bg-uofg-grey [&>svg]:tw-h-[1em] [&>svg]:tw-fill-current [&>svg]:tw-transition-transform [&>svg]:aria-expanded:tw-rotate-180"
                          slot="button"
                        >
                          <span>{item.text.toUpperCase()}</span>
                          <FontAwesomeIcon icon={faCaretDown} />
                        </button>
                        <ul
                          slot="content"
                          class="tw-absolute tw-right-0 tw-top-full tw-z-50 tw-flex tw-min-w-[20rem] tw-flex-col tw-bg-uofg-grey [&>li]:tw-contents"
                        >
                          {item.links.map(link => (
                            <li>
                              <a
                                class="tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-500 tw-p-4 tw-transition-colors hover:tw-bg-uofg-yellow"
                                href={link.href}
                              >
                                {link.text}
                              </a>
                            </li>
                          ))}
                        </ul>
                      </uofg-menu>
                    </li>
                  );
                }

                return (
                  <li>
                    <a
                      href={item.href}
                      class={`tw-flex tw-items-center tw-justify-center tw-p-4 tw-transition-colors hover:tw-bg-uofg-grey ${item.highlight ? 'tw-bg-uofg-yellow tw-px-6 tw-font-bold' : ''}`}
                    >
                      {item.text.toUpperCase()}
                    </a>
                  </li>
                );
              })}
            </ul>
          </div>
        )}

        {/*Main Navigation Bar*/}
        <nav
          class={{
            'tw-h-[10rem]': this.isFullSize,
            'tw-h-[5rem]': !this.isFullSize,
            'tw-relative tw-flex tw-justify-between tw-bg-black tw-px-[calc((100%-1320px)/2)] tw-text-3xl tw-text-white':
              true,
          }}
          aria-label="Main"
        >
          {/* Logo */}
          <div class="tw-flex tw-w-fit">
            {this.isFullSize && (
              <div
                class="tw-left-0 tw-h-full tw-w-[7.5rem] min-[1320px]:tw-absolute [&>svg]:tw-block [&>svg]:tw-h-full [&>svg]:tw-w-auto"
                innerHTML={Decoration}
              ></div>
            )}

            <a
              class="tw-h-full tw-w-fit tw-transition-opacity hocus:tw-opacity-75 min-[1320px]:tw-absolute min-[1320px]:tw-left-[max(calc((100%-1320px)/2),7.5rem)] [&>svg]:tw-block [&>svg]:tw-h-full [&>svg]:tw-w-auto"
              href="https://www.uoguelph.ca"
              innerHTML={this.isFullSize ? FullSizeLogo : ReducedSizeLogo}
              aria-label="University of Guelph Home Page"
            ></a>
          </div>

          {/* Main Navigation Content */}
          {this.isFullSize ? (
            <ul class="tw-flex tw-items-center tw-justify-center tw-text-4xl [&>li]:tw-contents">
              {mainLinks.map(item => (
                <li>
                  <a
                    href={item.href}
                    class="tw-flex tw-h-full tw-items-center tw-justify-center tw-border-0 tw-border-b-8 tw-border-solid tw-border-transparent tw-p-4 tw-pt-8 tw-transition-colors hover:tw-border-uofg-yellow hover:tw-text-uofg-yellow"
                  >
                    {item.text}
                  </a>
                </li>
              ))}
              {iconButtons.map(item => (
                <li>
                  <a
                    class="tw-flex tw-h-full tw-items-center tw-justify-center tw-border-0 tw-border-b-8 tw-border-solid tw-border-transparent tw-p-4 tw-pt-8 tw-text-uofg-yellow tw-transition-colors hover:tw-border-uofg-yellow hover:tw-text-white [&>svg]:tw-h-[1em] [&>svg]:tw-fill-current"
                    href={item.href}
                    aria-label={item.text}
                  >
                    <FontAwesomeIcon icon={item.icon as IconDefinition} />
                  </a>
                </li>
              ))}
            </ul>
          ) : (
            <div class="tw-flex tw-h-full">
              {iconButtons.map(item => (
                <a
                  class="tw-flex tw-aspect-square tw-h-full tw-items-center tw-justify-center tw-border-0 tw-border-l tw-border-solid tw-border-uofg-grey-950 tw-px-5 tw-transition-colors [&>svg]:tw-h-[1em] [&>svg]:tw-fill-current"
                  href={item.href}
                  aria-label={item.text}
                >
                  <FontAwesomeIcon icon={item.icon as IconDefinition} />
                </a>
              ))}

              {/* Main menu */}
              <uofg-menu class="tw-block tw-h-full" auto-collapse={true}>
                <button
                  slot="button"
                  aria-label="Main Menu"
                  class="tw-flex tw-aspect-square tw-h-full tw-items-center tw-justify-center tw-border-0 tw-border-l tw-border-solid tw-border-uofg-grey-950 tw-px-5 tw-transition-colors aria-expanded:tw-bg-white aria-expanded:tw-text-black [&>svg]:tw-h-[1em] [&>svg]:tw-fill-current"
                >
                  <FontAwesomeIcon icon={faBars} />
                </button>
                <div
                  slot="content"
                  class="tw-absolute tw-left-0 tw-top-full tw-z-50 tw-flex tw-max-h-[calc(100vh-5rem)] tw-w-full tw-flex-col tw-overflow-y-auto tw-bg-white tw-px-4 tw-text-black tw-shadow-md"
                >
                  <span class="tw-my-4 tw-text-4xl tw-font-bold">University of Guelph</span>

                  <ul class="tw-flex tw-w-full tw-flex-col tw-pb-6 [&>li]:tw-contents">
                    {mainLinks.map(item => (
                      <li>
                        <a
                          href={item.href}
                          class={`tw-w-full tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-400 tw-p-5 tw-transition-colors hover:tw-bg-uofg-grey ${item?.highlight ? 'tw-bg-uofg-yellow' : ''}`}
                        >
                          {item.text}
                        </a>
                      </li>
                    ))}

                    {topLinks.map(item => {
                      if ('links' in item) {
                        return (
                          <li>
                            <uofg-menu class="tw-relative tw-block tw-h-full tw-text-black" auto-collapse={false}>
                              <button
                                class="tw-flex tw-h-auto tw-w-full tw-items-center tw-justify-between tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-400 tw-p-5 tw-transition-colors hover:tw-bg-uofg-grey aria-expanded:tw-bg-uofg-grey [&>svg]:tw-h-[1em] [&>svg]:tw-fill-current [&>svg]:tw-transition-transform [&>svg]:aria-expanded:tw-rotate-180"
                                slot="button"
                              >
                                <span>{item.text}</span>
                                <FontAwesomeIcon icon={faCaretDown} />
                              </button>
                              <ul slot="content" class="tw-flex tw-w-full tw-flex-col [&>li]:tw-contents">
                                {item.links.map(link => (
                                  <li>
                                    <a
                                      class="tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-400 tw-p-5 tw-transition-colors hover:tw-bg-uofg-grey"
                                      href={link.href}
                                    >
                                      {link.text}
                                    </a>
                                  </li>
                                ))}
                              </ul>
                            </uofg-menu>
                          </li>
                        );
                      }

                      return (
                        <li>
                          <a
                            href={item.href}
                            class={`tw-w-full tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-400 tw-p-5 tw-transition-colors hover:tw-bg-uofg-grey ${item?.highlight ? 'tw-bg-uofg-yellow tw-font-bold' : ''}`}
                          >
                            {item.text}
                          </a>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              </uofg-menu>
            </div>
          )}
        </nav>

        {/* Bottom Navigation Bar */}
        {this.pageSpecificContent.length > 0 && (
          <nav
            ref={node => (this.subContainer = node)}
            aria-label="Department/Topic"
            class="tw-align-items tw-relative tw-flex tw-h-[5rem] tw-justify-end tw-bg-uofg-grey tw-px-[calc((100%-1320px)/2)] tw-text-3xl lg:tw-h-16 lg:tw-whitespace-nowrap"
          >
            {this.pageTitle &&
              (this.pageUrl != '' ? (
                <a
                  class="tw-mr-auto tw-flex tw-h-full tw-items-center tw-justify-center tw-px-4 tw-font-bold tw-transition-colors hover:tw-bg-uofg-yellow"
                  href={this.pageUrl}
                >
                  {this.pageTitle}
                </a>
              ) : (
                <span class="tw-mr-auto tw-flex tw-h-full tw-items-center tw-justify-center tw-px-4">
                  {this.pageTitle}
                </span>
              ))}

            {this.isFullSize && !this.isSubContainerOverflowing ? (
              <ul class="tw-flex tw-items-center tw-justify-center [&>li]:tw-contents">
                {this.pageSpecificContent?.map(item => {
                  if ('text' in item) {
                    return (
                      <li>
                        <a
                          class="tw-flex tw-h-full tw-items-center tw-justify-center tw-gap-2 tw-px-4 tw-transition-colors hover:tw-bg-uofg-yellow"
                          href={item.href}
                          {...item.attributes}
                        >
                          {item.text}
                        </a>
                      </li>
                    );
                  }

                  return (
                    <li>
                      <uofg-menu class="tw-relative tw-h-full" auto-collapse={true}>
                        <button
                          class="tw-flex tw-h-full tw-items-center tw-justify-center tw-gap-2 tw-px-4 tw-transition-colors hover:tw-bg-uofg-yellow aria-expanded:tw-bg-uofg-yellow [&>svg]:tw-h-[1em] [&>svg]:tw-fill-current"
                          slot="button"
                        >
                          <span>{item?.title}</span>
                          <FontAwesomeIcon icon={faCaretDown} />
                        </button>
                        <ul
                          slot="content"
                          class={{
                            'tw-absolute tw-right-0 tw-top-full tw-z-50 tw-flex tw-min-w-[20rem] tw-flex-col tw-bg-uofg-grey [&>li]:tw-contents':
                              true,
                            'wrap-content': item.wrapContent || false,
                          }}
                        >
                          {item.links.map(link => (
                            <li>
                              <a
                                class="tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-500 tw-p-4 tw-transition-colors hover:tw-bg-uofg-yellow"
                                href={link.href}
                                {...link.attributes}
                              >
                                {link.text}
                              </a>
                            </li>
                          ))}
                        </ul>
                      </uofg-menu>
                    </li>
                  );
                })}
              </ul>
            ) : (
              <uofg-menu class="tw-block tw-whitespace-normal tw-h-full lg:tw-relative" auto-collapse={true}>
                <button
                  class="tw-flex tw-aspect-square tw-h-full tw-items-center tw-justify-center tw-border-0 tw-border-l tw-border-solid tw-border-uofg-grey-300 tw-px-6 tw-transition-colors aria-expanded:tw-bg-uofg-yellow lg:tw-border-l-0 [&>svg]:tw-h-[1em] [&>svg]:tw-fill-current"
                  slot="button"
                  aria-label={this.pageTitle + ' Menu'}
                >
                  <FontAwesomeIcon icon={faBars} />
                </button>
                <ul
                  class="tw-absolute tw-right-0 tw-top-full tw-z-50 tw-flex tw-w-full tw-flex-col tw-bg-white tw-px-4 tw-text-black tw-shadow-md lg:tw-w-[30rem] [&>li]:tw-contents"
                  slot="content"
                >
                  {this.pageSpecificContent?.map(item => {
                    if ('text' in item) {
                      return (
                        <li class="[&>a]:last:tw-pb-4">
                          <a
                            href={item.href}
                            class="tw-w-full tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-400 tw-p-5 tw-transition-colors hover:tw-bg-uofg-grey"
                          >
                            {item.text}
                          </a>
                        </li>
                      );
                    }

                    return (
                      <li class="[&>uofg-menu]:last:tw-pb-6">
                        <uofg-menu class="tw-relative tw-block tw-h-full tw-text-black" auto-collapse={false}>
                          <button
                            class="tw-flex tw-h-auto tw-w-full tw-items-center tw-justify-between tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-400 tw-p-5 tw-transition-colors hover:tw-bg-uofg-grey aria-expanded:tw-bg-uofg-grey [&>svg]:tw-h-[1em] [&>svg]:tw-fill-current [&>svg]:tw-transition-transform [&>svg]:aria-expanded:tw-rotate-180"
                            slot="button"
                          >
                            <span>{item.title}</span>
                            <FontAwesomeIcon icon={faCaretDown} />
                          </button>
                          <ul slot="content" class="tw-flex tw-w-full tw-flex-col [&>li]:tw-contents">
                            {item.links.map(item => (
                              <li>
                                <a
                                  class="tw-border-0 tw-border-b tw-border-solid tw-border-uofg-grey-400 tw-p-5 tw-transition-colors hover:tw-bg-uofg-grey"
                                  href={item.href}
                                >
                                  {item.text}
                                </a>
                              </li>
                            ))}
                          </ul>
                        </uofg-menu>
                      </li>
                    );
                  })}
                </ul>
              </uofg-menu>
            )}
          </nav>
        )}
      </header>
    );
  }
}
