// src/components/uofg-alert.svelte
<svelte:options
  customElement={{
    tag: 'uofg-alert',
    extend: customElementConstructor => {
      return class extends customElementConstructor {
        constructor() {
          super();
          attachTailwind(this.shadowRoot);
        }
      };
    },
  }}
/>

<script>
  import attachTailwind from '../lib/attach-tailwind.js';
  import FontAwesomeIcon from '../lib/font-awesome-icon.svelte';
  import { faCircleExclamation } from '@fortawesome/free-solid-svg-icons';
</script>

<div class="flex flex-col text-3xl">
  <div
    class="flex items-center bg-uofg-red p-8 text-4xl text-white [&>svg]:mr-4 [&>svg]:h-[1.5em] [&>svg]:fill-current"
  >
    <FontAwesomeIcon icon={faCircleExclamation} />
    <slot name="title" />
  </div>

  <div
    class={`flex flex-col bg-white px-8 py-6 [&>slot[name="message"]::slotted(*)]:text-2xl [&>slot[name="subtitle"]::slotted(*)]:mb-8 [&>slot[name="subtitle"]::slotted(*)]:text-4xl [&>slot[name="subtitle"]::slotted(*)]:font-bold`}
  >
    <slot name="subtitle" />
    <slot name="message" />
  </div>

  <div class="flex bg-uofg-grey px-8 py-4 text-2xl">
    <slot name="footer" />
  </div>
</div>

// src/components/uofg-alert/uofg-alert.tsx
import { Component, Element, h } from '@stencil/core';
import { FontAwesomeIcon } from 'utils/font-awesome-icon';
import { faCircleExclamation } from '@fortawesome/free-solid-svg-icons';
import { attachTailwind } from '../../utils/utils';

@Component({ tag: 'uofg-alert', shadow: true })
export class UofgAlert {
  @Element() el: HTMLUofgAlertElement;

  connectedCallback() {
    attachTailwind(this.el.shadowRoot as ShadowRoot);
  }
  render() {
    return (
      <div class="tw-flex tw-flex-col tw-text-3xl">
        <div class="tw-flex tw-items-center tw-bg-uofg-red tw-p-8 tw-text-4xl tw-text-white [&>svg]:tw-mr-4 [&>svg]:tw-h-[1.5em] [&>svg]:tw-fill-current">
          <FontAwesomeIcon icon={faCircleExclamation} />
          <slot name="title"></slot>
        </div>

        <div class='tw-flex tw-flex-col tw-bg-white tw-px-8 tw-py-6 [&>slot[name="message"]::slotted(*)]:tw-text-2xl [&>slot[name="subtitle"]::slotted(*)]:tw-mb-8 [&>slot[name="subtitle"]::slotted(*)]:tw-text-4xl [&>slot[name="subtitle"]::slotted(*)]:tw-font-bold'>
          <slot name="subtitle"></slot>
          <slot name="message"></slot>
        </div>

        <div class="tw-flex tw-bg-uofg-grey tw-px-8 tw-py-4 tw-text-2xl">
          <slot name="footer"></slot>
        </div>
      </div>
    );
  }
}
